# Generated by Django 4.2.17 on 2024-12-15 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='files',
            new_name='github_link',
        ),
    ]
